### ISSUE TITLE
Fix domain issue

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#10]
There still seems to be an issue with the domain.
When hitting openclimatefix.org it simply redirects to openclimatefix.github.io.

It should be possible to stay on openclimatefix.org directly.

I think we should probably fix that.

**Comment by JackKelly** [comment]
Roger that - I'll look into this.  (I got it working on my personal website, jack-kelly.com, I just need to remember how I did it!)

**Comment by JackKelly** [comment]
OK, I _think_ this is setup correctly now!  It's still behaving a little strangely, but I think we just need to wait a few hours for the changes to propagate!

I'll check these things tomorrow (or early next week):

Under openclimatefix.github.io -> Settings -> Options:

* Check that this warning goes away: 'Domain does not resolve to the GitHub Pages server.'  (Under the GitHib Pages section)
* I have clicked 'Enforce HTTPS'.  This seems to be triggering an 'privacy error' when I try to load OpenClimateFix.org in a browser.  Check that this error goes away!

**Comment by JackKelly** [comment]
after re-starting Chrome on my Mac, I can now load https://openclimatefix.org fine :)  (And https://openclimatefix.org also works on my Android phone.).  I'll check again in the morning :)

**Comment by flowirtz** [comment]
Works for me as well now, thanks @JackKelly! Will close this issue.
