### ISSUE TITLE
Add proper OpenGraph support

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#11]
Currently, our open graph support is... mediocre.

![image](https://user-images.githubusercontent.com/6052785/67436036-6312c080-f5e5-11e9-9d49-6f406d7af6ad.png)

This is how e.g. Twitter renders our website. Not fun.

We should add proper support for the [OpenGraph Tags](http://ogp.me/) so that at least a little preview image will be rendered as well.

A good point to start for this will probably be the `SEO.jsx` component.

**Comment by drwm-base** [comment]
Can I work on this?

**Comment by flowirtz** [comment]
Sure definitely! Thanks for picking it up. I'll aim to review and merge your pr this evening so it's still within hacktoberfest. :-)

**Comment by drwm-base** [comment]
Thanks! I hope to contribute more to this project in the future!

**Comment by flowirtz** [comment]
that would be awesome!
