### ISSUE TITLE
Add cloud video to nowcasting page

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#14]
Let's include the video on our nowcasting project page here: https://github.com/openclimatefix/website/blob/master/src/pages/projects/nowcasting.jsx

https://www.youtube.com/watch?v=6Wz8KajCKgQ

(Raised from #1)

**Comment by JackKelly** [comment]
Woops!  My bad:  The PV data and satellite data were out-of-sync by an hour in that old video!  [Here's a new, improved video](https://www.youtube.com/watch?v=IOp-tj-IJpk).  Please use the new video instead!

https://github.com/openclimatefix/predict_pv_yield/issues/2
