### ISSUE TITLE
RSS feed for the blog

### ISSUE THREAD

**Issue by ollicle** [openclimatefix/website#35]
**Is your feature request related to a problem? Please describe.**
A RSS feed of blog content provides:

- Timely notifications and syndication of fresh blog content for those interested in updates. 
- Easy discover-ability for and integration with existing systems for consuming blog content.

**Describe the solution you'd like**
- A standard RSS feed generated from most recent blog posts (10 perhaps).
- A `<link>` in the `<head>` and footer link will help folks (and machines) find the feed xml.

**Describe alternatives you've considered**
- [JSON Feed](https://jsonfeed.org/) is also worth considering. Both would be ideal

**Additional context**
- The death of RSS was over stated :)

**Comment by flowirtz** [comment]
Great idea @ollicle, thanks for raising!
This likely would be a good point to start: https://www.gatsbyjs.org/docs/adding-an-rss-feed/
