### ISSUE TITLE
Create Contributors Showcase Component

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#38]
We want to have a gallery like view of all Contributors.
This should look similar to the below screenshot (red box) and include:
- 100x100px Avatar of Contributors (`avatar_url`)
- their name (`name`)
- a link to their profile (`profile`)

## Data
The data for this will come from a static JSON file with the following array syntax inside:
```json
{
"contributors": [
    {
      "login": "JackKelly",
      "name": "Jack Kelly",
      "avatar_url": "https://avatars2.githubusercontent.com/u/460756?v=4",
      "profile": "http://jack-kelly.com",
      "contributions": [
        "business",
        "code",
        "content",
        "ideas"
      ]
    },
  ]
}
```
([Bigger Example](https://github.com/openclimatefix/website/blob/master/.all-contributorsrc))

## Mockup
<img width="664" alt="Screenshot 2019-11-12 at 20 26 08" src="https://user-images.githubusercontent.com/6052785/68708011-bf388700-058a-11ea-963a-a9913c56290c.png">

---
Parent Epic: #3

**Comment by drwm-base** [comment]
@FWirtz I would like to be assigned to this issue!
