### ISSUE TITLE
Fix footer not always sticking to the bottom

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#5]
When the page content is fairly small, the footer doesn't stick to the bottom of the page.

![image](https://user-images.githubusercontent.com/6052785/67118031-f90cac80-f1db-11e9-97ba-62481b8974e6.png)

In this case we want the footer to be at the bottom of the viewport, not floating above it as seen.

**Comment by flowirtz** [comment]
Hey @geekayush, would you still like to work on this? 😊

**Comment by flowirtz** [comment]
Hey @geekayush I'll unassign you for now, feel free to ping me if you want to pick it up again.

**Comment by ollicle** [comment]
The CSS necessary to make this happen:
```
html,
body,
#___gatsby,
#gatsby-focus-wrapper  {
  height: 100%;
}

 #gatsby-focus-wrapper {
  display: flex;
  flex-direction: column;
}

main {
  flex: auto;
}
```
I’ll leave it to someone who knows their way around tailwind and/or react to implement :)

**Comment by ollicle** [comment]
Alternatively with CSS grid:
```
html,
body,
#___gatsby,
#gatsby-focus-wrapper  {
  height: 100%;
}

#gatsby-focus-wrapper {
  min-height: 100%;
  display: grid;
  grid-template-rows: auto 1fr auto;
  grid-template-columns: 100%;
}
```

**Comment by geekayush** [comment]
@FWirtz Got stuck up into some important work. I am taking this up.
@ollicle Hey, Thanks!

**Comment by flowirtz** [comment]
@geekayush ah even better! Thanks so much. No worries at all. I appreciate your help!
