### ISSUE TITLE
Add blog post filter by category

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#62]
On the /blog page we are currently displaying all blog posts that exist.
Luckily the number of them is growing fairly quickly. That makes going through them a bit hard though.

We should expect that some visitors are only interested in certain topics, not all of them.
That's why it would be good to be able to filter blog posts by project.

![image](https://user-images.githubusercontent.com/6052785/88191697-9f865200-cc33-11ea-9edc-3cec3d145cef.png)

It would be good to have a row that says "Filter by Project:" and then all the projects as buttons next to it, similarly to the above (hacky) screenshot. When a user clicks on one of these buttons the blog posts should be filtered by project. There should also be a reset button to remove the filter.

We already have a `project: 'open-energy'` metadata field on every blog post that should be queryable via GraphQL.

**Comment by melnyczuk** [comment]
Hi, I'm happy to pick this up!

I have a question about the desired filtering UX:
would you like the filters to be mutually exclusive (ie, radio button type interaction) 
or 
would you like the filters to be opt-in/opt-out (ie, check-box type interaction)

I've got the filtering working fine, and figure that a row of buttons across the top of the blog posts as the image above suggests:
<img width="686" alt="Screenshot 2021-05-20 at 18 16 26" src="https://user-images.githubusercontent.com/23401306/119013671-20ff5b80-b98f-11eb-9fb1-a310496c14a1.png">
note: work in progress (needs padding and correct colours & sizing)

(ps, hi 👋 not sure if I should introduce myself somewhere?)

**Comment by flowirtz** [comment]
Hey Howard,

first off: I'm really sorry it took me so long to get back to you. I promise I'm usually faster than that.

Thanks so much for picking this up! I already looked at your PR as well. I think radio-style is best, like you already did anyways.

Thanks!

**Comment by flowirtz** [comment]
Resolved via #88
