### ISSUE TITLE
Improve Metadata Handling

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#63]
When sharing a link on e.g. Twitter an automatic preview is generated.
This is largely based on Open Graph Tags.

We have hardcoded these tags.
Therefore, if we share a link to e.g. a blog post, the default description is shown.

![image](https://user-images.githubusercontent.com/6052785/88393651-ed2ac800-cdb5-11ea-9532-42042477364e.png)
https://openclimatefix.org/blog/2020-07-22-getting-to-the-grid-of-the-future

At least for blog posts, we should change that.
It would be better to show a preview of the respective post.
Also, instead of showing the OCF logo, it would be nicer to show the cover image of the post.

**Relevant Links**
- [Metadata testing tool](https://metatags.io/)
- [Gatsby guide on SEO component](https://www.gatsbyjs.org/docs/add-seo-component/)

We already have a `SEO` component that we can likely extend for this.

**Comment by mantagen** [comment]
https://deploy-preview-78--openclimatefix.netlify.app/blog/2021-01-05-values

![image](https://user-images.githubusercontent.com/12934669/108577224-28738200-7318-11eb-93d2-9ab4ce488d3f.png)

I wonder if it would be better to remove the word "Blog" from the beginning of the title?
