### ISSUE TITLE
Side Scrolling of Homepage image

### ISSUE THREAD

**Issue by animeshdas2000** [openclimatefix/website#74]
**Side Scrolling is visible due to the width of the parallax image**

**Comment by flowirtz** [comment]
Hey! Thanks for raising this. Could you explain the issue a bit more?

I did not notice any side-scrolling visible.

**Comment by animeshdas2000** [comment]
This may differ from device to device, following are the two screenshots from my laptop.
If you could assign me I'd love to work on this.

![image](https://user-images.githubusercontent.com/40542456/96128598-30a75500-0f13-11eb-8a76-a96cf135d65d.png)
![image](https://user-images.githubusercontent.com/40542456/96128624-3735cc80-0f13-11eb-82b1-8b2cd0b42857.png)

**Comment by flowirtz** [comment]
Aaaah, I see. Thanks for reporting!

**Comment by mantagen** [comment]
Preview of #77 at https://deploy-preview-77--openclimatefix.netlify.app/
