### ISSUE TITLE
Add link to YouTube to footer

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#8]
Our footer already has a bunch of icons:

![image](https://user-images.githubusercontent.com/6052785/67435023-35c51300-f5e3-11e9-81f8-a8bc8008c8f1.png)

We should also probably add a link to our YouTube channel down there as well.

https://www.youtube.com/channel/UCq2-AN_j8BMERxTqdSvtPAg

**Comment by hansal7014** [comment]
Hi @FWirtz ,
I can work on this issue. Please assign it to me.
Thanks.
