### ISSUE TITLE
Acknowledge the NVIDIA Academic Hardware Grant Program

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/website#91]
**Describe the solution you'd like**
Add the "NVIDIA Academic Hardware Grant Program" to the list of "Supporters" on openclimatefix.org

**Additional context**
The lovely folks at the NVIDIA Academic Hardware Grant Program have given OCF two A6000 GPUs!  Thanks so much, NVIDIA!  :)

The nvidia email explicitly encourages us to acknowledge the NVIDIA Academic Hardware Grant Program whenever we can :)

**Comment by flowirtz** [comment]
implemented on new website
